### ISSUE TITLE
blockly build FATAL ERROR

### ISSUE THREAD

**Issue by zhengyongxiong** [RealTimeWeb/blockpy#39]
I installed according to your tutorial. When I built this step, I got this error. Why is this? There is a directory in your tutorial that seems to be inconsistent with the download, such as the directory of en.js.
![01](https://user-images.githubusercontent.com/13392637/49990630-50892d00-ffb9-11e8-8874-112828a5b5b9.png)
![02](https://user-images.githubusercontent.com/13392637/49990632-50892d00-ffb9-11e8-9545-0233d9ea69d9.png)
![03](https://user-images.githubusercontent.com/13392637/49990633-5121c380-ffb9-11e8-8bb6-6c67cafb251c.png)

**Comment by kushal4** [comment]
r u using the latest version of google blockly code ?

**Comment by zhengyongxiong** [comment]
yes, the latest version of google blockly code

**Comment by lukesg08** [comment]
I fixed the instructions of the readme. Please follow the updated instructions. Please comment on whether it works or whether you have any issues with the new instructions.

**Comment by zhengyongxiong** [comment]
> 我修改了自述文件的说明。请按照更新的说明进行操作 请评论它是否有效或是否与新指令有任何问题。

May I contact you? Are you in touch with me by email?
