### ISSUE TITLE
python skulpt.py dist erro

### ISSUE THREAD

**Issue by zhengyongxiong** [RealTimeWeb/blockpy#42]
![image](https://user-images.githubusercontent.com/13392637/55523142-70ed0c80-56ba-11e9-8537-8a25503c3560.png)
![image](https://user-images.githubusercontent.com/13392637/55523147-74809380-56ba-11e9-8250-0c3861286d8f.png)
![image](https://user-images.githubusercontent.com/13392637/55523152-78141a80-56ba-11e9-8b11-4ad49bd3508a.png)
![image](https://user-images.githubusercontent.com/13392637/55523159-7ba7a180-56ba-11e9-9ec5-1e02a88813da.png)
![image](https://user-images.githubusercontent.com/13392637/55523164-806c5580-56ba-11e9-892b-8761a7d8386d.png)
I followed the steps of readme. Did I make a mistake at this step? What's the matter?

**Comment by lukesg08** [comment]
readme is updated. blockly builds in python2, while skulpt builds in python3.

**Comment by zhengyongxiong** [comment]
> readme is updated. blockly builds in python2, while skulpt builds in python3.

![image](https://user-images.githubusercontent.com/13392637/55524800-2458ff80-56c1-11e9-8470-6ac815cb554c.png)
python 2.7

**Comment by zhengyongxiong** [comment]
What's wrong now is python skulpt.py dist

**Comment by lukesg08** [comment]
This should be run using python 2 (The version of python you're currently running)

`    > cp blockly/msg/js/en.js en.js`
`    > cd blockly`
`    > python build.py`
`    > cd ..`
`    > mv -force en.js blockly/msg/js/en.js`

This should be run using python 3
`python skulpt.py dist`

**Comment by zhengyongxiong** [comment]
> This should be run using python 2 (The version of python you're currently running)
> 
> ` > cp blockly/msg/js/en.js en.js`
> ` > cd blockly`
> ` > python build.py`
> ` > cd ..`
> ` > mv -force en.js blockly/msg/js/en.js`
> 
> This should be run using python 3
> `python skulpt.py dist`

![image](https://user-images.githubusercontent.com/13392637/55525665-8ff09c00-56c4-11e9-8e4b-4ef8313087dd.png)

**Comment by zhengyongxiong** [comment]
![image](https://user-images.githubusercontent.com/13392637/55526016-e7433c00-56c5-11e9-9f4e-754709dac5d0.png)
ok
