### ISSUE TITLE
Question: How to run locally.

### ISSUE THREAD

**Issue by tildebyte** [RealTimeWeb/blockpy#9]
As subject. I've cloned locally, but I'm at a loss as to how to start it up.

**Comment by acbart** [comment]
Great question! I need to update the readme with instructions. Currently at lunch with family, should be home soon and I can fix it. Should be straightforward to open blockpy.html but you may have to run the build commands for Skulpt and blockly. Do you just want to try out the interface, or are you also interested in the server?

**Comment by tildebyte** [comment]
Well, I did look at the interface, but it seemed like there was some functionality missing...? I assumed due to the server being unavailable.

**Comment by acbart** [comment]
I'm guessing the missing functionality was skulpt not being built correctly. I'm writing the documentation now, and also pushing a change that'll fix my most recent additions to skulpt (I've been instrumenting the parser to report line/column ending for tokens). This shouldn't be too much longer, so I'll be interested in hearing your experiences with things so far. Most of my use has been targeted to our classroom, so I've been the only one touching things.

**Comment by tildebyte** [comment]
Cool! I'll take a look. My 9-yr-old's bio-dad will probably run through it with him a bit (he's been exposed to Squeak, I believe).

**Comment by acbart** [comment]
Okay, so I just pushed some missing libraries (bad gitignore) that should make everything work. Please pull and take a look at your convenience. I'll be very interested in hearing what they think. Squeak/Scratch/Snap have a very strong visual/arts/music/creativity bent that is different from our vision of data science, but the interface itself is meant to be comparable.

**Comment by tildebyte** [comment]
Will do.

**Comment by tildebyte** [comment]
OK, I think I did everything correctly (although remembering that the presence of a `requirements.txt` means `pip install -r requirements.txt` took me a while), but I don't understand `start blockpy.html`...

**Comment by acbart** [comment]
Sorry, windows terminology. Simply open blockpy.html in your browser!

**Comment by tildebyte** [comment]
Ah, derp. Been doing cross-platform for so long, I'm starting to forget which things go where.

**Comment by tildebyte** [comment]
Hmm. I still don't think that the server is working properly. I have `Loading...` stuck in the top right of the blocks "frame". However, the example code does run.

**Comment by acbart** [comment]
The server has different instructions, but it's not very exciting yet since
it doesn't do any saving. Everything with Blockpy works locally, except
saving and some of the advanced real-time functionality for accessing
weather data (uses cache data otherwise), but those aren't ready yet. The
main goal is to keep everything local if possible. The server will be
handling LTI stuff mostly.

**Comment by tildebyte** [comment]
OH! OK, cool.
